# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.14.1-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/lt-tool-kit

    steps:
      - run:
          name: "Checking Versions (node && npm)"
          command: |
            node --version
            npm --version

      # Checkokut repository
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/lt-widget/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install project dependencies
      - run: cd packages/lt-widget && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "packages/lt-widget/package.json" }}

      # Check for updates!
      - run:
          name: "Checking for npm packages not uptdated"
          command: cd packages/lt-widget && npm run check-updates

      # Run tests!
      - run:
          name: "Running tests"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: cd packages/lt-widget && npm run test:ci

      # Save the generated file for use in the deploy job
      - persist_to_workspace:
          root: .
          paths: packages/lt-widget

      # Create temp directories
      - run: |
          mkdir -p /tmp/artifacts
          mkdir -p /tmp/test-reports
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: /tmp/artifacts
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.14.1-stretch-browsers

    working_directory: ~/lt-tool-kit

    steps:
      - attach_workspace:
          at: ~/lt-tool-kit

      # Upload to AmazonS3
      - run:
          name: "Uploading dist/widget.js to AmazonS3"
          command: cd packages/lt-widget && npm run build:release


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
